export const Screens = {
  HOME: 'Home',
  SPLASH: 'Splash',
  LOGIN: 'Login',
  REGISTER_WALLET: 'RegisterWallet',
  SECURE_WALLET: 'SecureWallet',
  CONFIRM_PHRASE: 'ConfirmPhrase',
  RECOVERY_WALLET: 'RecoveryWallet',
  CONFIRM_WALLET: 'ConfirmWallet',
  SUCCESS_WALLET: 'SuccessWallet',
  EDIT_PROFILE: 'EditProfile',
  REGISTER_SUCCESS: 'RegisterSuccess',
  HOMEPAGE: 'HomePage',
  WALLET_PAGE: 'WalletPage',
  PROFILE_PAGE: 'ProfilePage',
  SEARCH_PAGE: 'SearchPage',
  CHANGE_PASSWORD: 'ChangePassword',
  NOTIFICATION_PROFILE: 'NotificationProfile',
  NOTIFICATION_DETAIL: 'NotificationDetail',
  KYC_ACCOUNT: 'KycAccount',
  RECOVERY_SEED_PHRASE: 'RecoverySeedPhrase',
  SECURITY_PAGE: 'SecurityPage',
  SEND_TOKEN_PAGE: 'SendTokenPage',
  ADDRESS_SEND: 'AddressSendPage',
  CHART_PAGE: 'ChartPage'
}
